### ISSUE TITLE
Package no longer returns news

### ISSUE THREAD

**Issue by mashegoindustries** [lewisdonovan/google-news-scraper#37]
As of 30 November - package no longer returns any news.

Since this relies on DOM selectors
I fundamental changes in the markup on the Google News site :(

**Comment by lewisdonovan** [comment]
Thanks for raising, I’ll investigate asap. In the mean-time if you are able to patch please raise a PR.

**Comment by lewisdonovan** [comment]
@mashegoindustries this issue has been fixed in 742a7faf44d0ff7aec86922750bf0692ec0753ef

Google had added an interstitial page to accept or reject cookies, and they had also updated the DOM selectors as you mentioned. 

Thanks again for flagging, I hope this unblocks you. Closing this issue for now, please reopen if you're still experiencing problems.
