### ISSUE TITLE
Pupeeter problem when app is deployed 

### ISSUE THREAD

**Issue by hakizimana-fred** [lewisdonovan/google-news-scraper#7]
message": "Failed to launch the browser process!\n/app/node_modules/puppeteer/.local-chromium/linux-756035/chrome-linux/chrome: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory\n\n\nTROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md\n"
I've deployed a script that depends on this package but I've been getting this constant error message, Yet the script runs fine locally.

**Comment by lewisdonovan** [comment]
Hi Fred.
I think this can be solved by passing the `'--no-sandbox'` and `'--disable-setuid-sandbox'` flags to Puppeteer when launching the browser instance. In [the latest commit](https://github.com/lewisdonovan/google-news-scraper/commit/f61e0bf3a8d3fd00b821d4c24485de1a312bd78b#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346R11), I've added a `puppeteerArgs` property to the config object to allow you to do this.

Your config object when calling the scraper should look something like this:
```javascript
const articles = await googleNewsScraper({
  searchTerm: "Your search term",
  prettyURLs: false,
  timeframe: "5d",
  puppeteerArgs: [
    '--no-sandbox',
    '--disable-setuid-sandbox'
  ]
})
```

Please try this and let me know if it works. I'll keep the ticket open until then. Thanks.

**Comment by hakizimana-fred** [comment]
Hi Lewis. Unfortunately it's producing the same error. not sure why this is
happenq really.

**Comment by hakizimana-fred** [comment]
Hi Lewis. Unfortunately it's producing the same error. not sure why this is happenq really.

**Comment by hakizimana-fred** [comment]
can you maybe try to deploy that little script on heroku or any other servers and see how it behaves?

**Comment by lewisdonovan** [comment]
Hi Fred. I got this working [on a Heroku instance](https://news-scraper-test.herokuapp.com/), but you need to take the following steps in your local build before pushing to Heroku:

1. Run `npm update` to ensure you're pulling the latest version of google-news-scraper.

2. Add the [puppeteer-heroku-buildpack](https://github.com/jontewks/puppeteer-heroku-buildpack) with the command `heroku buildpacks:add https://github.com/jontewks/puppeteer-heroku-buildpack.git`

3. Ensure you're passing the `'--no-sandbox''` and `'--disable-setuid-sandbox'` in the config object (as described in my previous reply).

You'll notice your Heroku build will take a lot longer due to the additional buildpack, but once it's done you should have a working instance.

The code I used in the `index.js` file in my Heroku instance is below:

```javascript
const express = require('express');
const googleNewsScraper = require("google-news-scraper");

// Start server
const app = express()
const port = process.env.PORT || 8080
app.listen(port, () => {
  console.log(`listening on port ${port}`)
})

app.get("/", async (req, res) => {
  const articles = await googleNewsScraper({
    searchTerm: req.query.searchterm || "tech news",
    prettyURLs: Boolean(req.query.prettyURLs) || false,
    timeframe: req.query.timeframe || "5d",
    puppeteerArgs: [
      '--no-sandbox',
      '--disable-setuid-sandbox'
    ]
  })
  res.status(200).json(articles)
})
```

I'm going to close this issue, but let me know if you hit any further issues. Thanks.

**Comment by hakizimana-fred** [comment]
Thank you so much. it worked. I noticed this package needs a faster
internet connection!
