### ISSUE TITLE
How can change language 

### ISSUE THREAD

**Issue by vickyraje** [lewisdonovan/google-news-scraper#8]
Hi,
     I am trying to change the language 
const url = `https://news.google.com/search?hl=ta&gl=IN&ceid=IN:ta&q=latestnews when:${config.timeframe || '1h'}` 
using this URL it's Tamil news display but the response shows English alone and then I am past gl=IN. India news only displays bt it shows all over the world news.
https://prntscr.com/10t7s9h

**Comment by lewisdonovan** [comment]
Hi Vicky,
I've added support for custom query parameters to be added to the URL. Please run `npm update` in your project in order to pull the latest version of `google-news-scraper` from NPM, and then run the code as described in the README file, paying particular attention to the new `queryVars` object in the config.

I'm going to close this issue, but let me know if I can help further.
